<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Use of undefined constant WPFORMS_PLUGIN_DIR - assumed 'WPFORMS_PLUGIN_DIR' (this will throw an Error in a future version of PHP) in /home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php on line <i>28</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0018</td><td bgcolor='#eeeeec' align='right'>356088</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php' bgcolor='#eeeeec'>.../class-templates.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0019</td><td bgcolor='#eeeeec' align='right'>356128</td><td bgcolor='#eeeeec'>WPForms_Templates->__construct(  )</td><td title='/home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php' bgcolor='#eeeeec'>.../class-templates.php<b>:</b>64</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0019</td><td bgcolor='#eeeeec' align='right'>356128</td><td bgcolor='#eeeeec'>WPForms_Templates->init(  )</td><td title='/home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php' bgcolor='#eeeeec'>.../class-templates.php<b>:</b>17</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: require_once(WPFORMS_PLUGIN_DIRincludes/templates/class-base.php): failed to open stream: No such file or directory in /home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php on line <i>28</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0018</td><td bgcolor='#eeeeec' align='right'>356088</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php' bgcolor='#eeeeec'>.../class-templates.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0019</td><td bgcolor='#eeeeec' align='right'>356128</td><td bgcolor='#eeeeec'>WPForms_Templates->__construct(  )</td><td title='/home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php' bgcolor='#eeeeec'>.../class-templates.php<b>:</b>64</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0019</td><td bgcolor='#eeeeec' align='right'>356128</td><td bgcolor='#eeeeec'>WPForms_Templates->init(  )</td><td title='/home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php' bgcolor='#eeeeec'>.../class-templates.php<b>:</b>17</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: require_once(): Failed opening required 'WPFORMS_PLUGIN_DIRincludes/templates/class-base.php' (include_path='.:/usr/share/php') in /home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php on line <i>28</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0018</td><td bgcolor='#eeeeec' align='right'>356088</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php' bgcolor='#eeeeec'>.../class-templates.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0019</td><td bgcolor='#eeeeec' align='right'>356128</td><td bgcolor='#eeeeec'>WPForms_Templates->__construct(  )</td><td title='/home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php' bgcolor='#eeeeec'>.../class-templates.php<b>:</b>64</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0019</td><td bgcolor='#eeeeec' align='right'>356128</td><td bgcolor='#eeeeec'>WPForms_Templates->init(  )</td><td title='/home/vagrant/code/statybos/public/wp-content/plugins/wpforms/includes/class-templates.php' bgcolor='#eeeeec'>.../class-templates.php<b>:</b>17</td></tr>
</table></font>
